// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: proto/publicapi/events.proto

package publicapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EventTypeUnknown    EventType = 0
	EventType_EventTypeAPIEnable  EventType = 1
	EventType_EventTypeAPIDisable EventType = 2
	EventType_EventTypeAPIUpdate  EventType = 3
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EventTypeUnknown",
		1: "EventTypeAPIEnable",
		2: "EventTypeAPIDisable",
		3: "EventTypeAPIUpdate",
	}
	EventType_value = map[string]int32{
		"EventTypeUnknown":    0,
		"EventTypeAPIEnable":  1,
		"EventTypeAPIDisable": 2,
		"EventTypeAPIUpdate":  3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_publicapi_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_proto_publicapi_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_publicapi_events_proto_rawDescGZIP(), []int{0}
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       EventType   `protobuf:"varint,1,opt,name=type,proto3,enum=publicapievents.EventType" json:"type,omitempty"`
	ApiEnable  *APIEnable  `protobuf:"bytes,2,opt,name=api_enable,json=apiEnable,proto3" json:"api_enable,omitempty"`
	ApiDisable *APIDisable `protobuf:"bytes,3,opt,name=api_disable,json=apiDisable,proto3" json:"api_disable,omitempty"`
	ApiUpdate  *APIUpdate  `protobuf:"bytes,4,opt,name=api_update,json=apiUpdate,proto3" json:"api_update,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_publicapi_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publicapi_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_publicapi_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EventTypeUnknown
}

func (x *Event) GetApiEnable() *APIEnable {
	if x != nil {
		return x.ApiEnable
	}
	return nil
}

func (x *Event) GetApiDisable() *APIDisable {
	if x != nil {
		return x.ApiDisable
	}
	return nil
}

func (x *Event) GetApiUpdate() *APIUpdate {
	if x != nil {
		return x.ApiUpdate
	}
	return nil
}

type APIEnable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *APIEnable) Reset() {
	*x = APIEnable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_publicapi_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIEnable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIEnable) ProtoMessage() {}

func (x *APIEnable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publicapi_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIEnable.ProtoReflect.Descriptor instead.
func (*APIEnable) Descriptor() ([]byte, []int) {
	return file_proto_publicapi_events_proto_rawDescGZIP(), []int{1}
}

func (x *APIEnable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type APIDisable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *APIDisable) Reset() {
	*x = APIDisable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_publicapi_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIDisable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIDisable) ProtoMessage() {}

func (x *APIDisable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publicapi_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIDisable.ProtoReflect.Descriptor instead.
func (*APIDisable) Descriptor() ([]byte, []int) {
	return file_proto_publicapi_events_proto_rawDescGZIP(), []int{2}
}

func (x *APIDisable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type APIUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *APIUpdate) Reset() {
	*x = APIUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_publicapi_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIUpdate) ProtoMessage() {}

func (x *APIUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publicapi_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIUpdate.ProtoReflect.Descriptor instead.
func (*APIUpdate) Descriptor() ([]byte, []int) {
	return file_proto_publicapi_events_proto_rawDescGZIP(), []int{3}
}

func (x *APIUpdate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_publicapi_events_proto protoreflect.FileDescriptor

var file_proto_publicapi_events_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x70,
	0x69, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x70, 0x69, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22,
	0xeb, 0x01, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x61, 0x70, 0x69, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x61, 0x70, 0x69,
	0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x70, 0x69, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x41, 0x50, 0x49, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x09, 0x61, 0x70, 0x69, 0x45, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x61, 0x70, 0x69, 0x5f, 0x64, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x61, 0x70, 0x69, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x41, 0x50, 0x49, 0x44,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x0a, 0x61, 0x70, 0x69, 0x44, 0x69, 0x73, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x61, 0x70, 0x69, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61,
	0x70, 0x69, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x41, 0x50, 0x49, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x09, 0x61, 0x70, 0x69, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x1f, 0x0a,
	0x09, 0x41, 0x50, 0x49, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x20,
	0x0a, 0x0a, 0x41, 0x50, 0x49, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x1f, 0x0a, 0x09, 0x41, 0x50, 0x49, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x2a, 0x6a, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14,
	0x0a, 0x10, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x55, 0x6e, 0x6b, 0x6e, 0x6f,
	0x77, 0x6e, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x41, 0x50, 0x49, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x41, 0x50, 0x49, 0x44, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x41, 0x50, 0x49, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x10, 0x03, 0x42, 0x13, 0x5a,
	0x11, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_publicapi_events_proto_rawDescOnce sync.Once
	file_proto_publicapi_events_proto_rawDescData = file_proto_publicapi_events_proto_rawDesc
)

func file_proto_publicapi_events_proto_rawDescGZIP() []byte {
	file_proto_publicapi_events_proto_rawDescOnce.Do(func() {
		file_proto_publicapi_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_publicapi_events_proto_rawDescData)
	})
	return file_proto_publicapi_events_proto_rawDescData
}

var file_proto_publicapi_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_publicapi_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_publicapi_events_proto_goTypes = []interface{}{
	(EventType)(0),     // 0: publicapievents.EventType
	(*Event)(nil),      // 1: publicapievents.Event
	(*APIEnable)(nil),  // 2: publicapievents.APIEnable
	(*APIDisable)(nil), // 3: publicapievents.APIDisable
	(*APIUpdate)(nil),  // 4: publicapievents.APIUpdate
}
var file_proto_publicapi_events_proto_depIdxs = []int32{
	0, // 0: publicapievents.Event.type:type_name -> publicapievents.EventType
	2, // 1: publicapievents.Event.api_enable:type_name -> publicapievents.APIEnable
	3, // 2: publicapievents.Event.api_disable:type_name -> publicapievents.APIDisable
	4, // 3: publicapievents.Event.api_update:type_name -> publicapievents.APIUpdate
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_publicapi_events_proto_init() }
func file_proto_publicapi_events_proto_init() {
	if File_proto_publicapi_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_publicapi_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_publicapi_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIEnable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_publicapi_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIDisable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_publicapi_events_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_publicapi_events_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_publicapi_events_proto_goTypes,
		DependencyIndexes: file_proto_publicapi_events_proto_depIdxs,
		EnumInfos:         file_proto_publicapi_events_proto_enumTypes,
		MessageInfos:      file_proto_publicapi_events_proto_msgTypes,
	}.Build()
	File_proto_publicapi_events_proto = out.File
	file_proto_publicapi_events_proto_rawDesc = nil
	file_proto_publicapi_events_proto_goTypes = nil
	file_proto_publicapi_events_proto_depIdxs = nil
}
