name: Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out repository
      - uses: elgohr/Publish-Docker-Github-Action@2.12
        name: Build and Push Docker Image
        with:
          name: micro/services
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true
  build-cockroach-backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out repository
      - uses: elgohr/Publish-Docker-Github-Action@2.18
        name: Build and Push Docker Image
        with:
          name: micro/cockroach-backup
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: database/backup
          snapshot: true
  build-cockroach-restore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out repository
      - uses: elgohr/Publish-Docker-Github-Action@2.18
        name: Build and Push Docker Image
        with:
          name: micro/cockroach-restore
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: database/restore
          snapshot: true
